# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a331ce5c930a44fe96ccd294abbef9fd41c986b88693a3ce49a3717608eb547a430838f9413912bf3da6eef33a4a9ab5643b91450806492bbe55fe063f7023e5

test:
  secret_key_base: 69d0c270e44f997337408f7b5fc7456ee649c241be20e9246a2cad887fbd2bea3a08a85dcbd3a4a5a827d7756fbe99a254b750d1c7b939c9e23a38087cca2dfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
